<?php 
/**
 * Edit View. Renders the view of the edit action 
 *
 * 
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<div class="row-fluid line">
    <div class="span12">
        <div class="page-header-wica center">
            <h1><?php echo $lang->translate('Update Alternative Web Semiotic Unit'); ?> </h1>		
        </div>
    </div>	
</div>

<div class="row-fluid line">
    <div class="span12"></div>	
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="well <?php echo $this->form->getAttrib('class'); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data">
            <div class="row-fluid">
                <div class="span12">
                    <div class="row-fluid">
                        <div id="step0" class="span12">
                            <div class="step_containers">
                                <div class="row-fluid">
                                    <div class="span6">
                                        <div class="control-group">
                                            <label class="control-label"><?php echo $this->form->original->getLabel(); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->original->renderViewHelper(); ?>
                                            </div>
                                        </div>
                                        <div class="controls">
                                            <?php echo $this->form->id->renderViewHelper(); ?>
                                            <?php echo $this->form->section_id->renderViewHelper(); ?>
                                            <?php echo $this->form->parent_id->renderViewHelper(); ?>
                                            <?php echo $this->form->level->renderViewHelper(); ?>
                                        </div>
                                    </div>
                                    <div class="span6">
                                        <div class="control-group">
                                            <label class="control-label"><?php echo $this->form->semiotic->getLabel(); ?></label>
                                            <div class="controls">
                                                <?php echo $this->form->semiotic->renderViewHelper(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="center well">
                    <div class="row-fluid">                                        
                        <?php echo $this->form->submit->renderViewHelper(); ?>
                        &nbsp;&nbsp;
                        <?php echo $this->form->cancel->renderViewHelper(); ?>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>