<?php 
/**
 * Index View. Renders the view of the index action 
 *
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<?php if ($this->ontology_list && count($this->ontology_list)>0): ?>

<div class="row-fluid">
	<div class="alert alert-info general_legend_text">
		<div class="legend_inner_left">
			<i class="icon-info-sign"></i>
		</div>
		<div class="right">
			<i class="icon-pencil"></i> <?php echo $lang->translate('Update'); ?> &nbsp;&nbsp;
			<i class="icon-trash"></i> <?php echo $lang->translate('Delete'); ?> &nbsp;&nbsp;
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Section list'); ?></h1>
	</div>
</div>
	
<form action="" method="post" name="frmSection" id="frmOntologyOrder">
	
	<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">
	
	<div class="row-fluid table-bordered-header">	
		<div class="span4"><b><?php echo $lang->translate('Section'); ?></b></div>
		<div class="span4 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
	</div>
	
	<div id="sortable">
        <?php
	$id = New Zend_Session_Namespace('id');
	$website_name_info = $id->website_name_info; 
        ?>
            <div class="row-fluid table-bordered-content odd" id="website">	
                <div class="span4 pointer"><a class="pointer" id="edit_ws" ontology_id=""> <?php if(isset($website_name_info)): echo $website_name_info; else: echo 'Website'; endif; ?> </a></div>
                <div class="span4 last pointer">
                    <a class="pointer" id="edit_ws" ontology_id="" title="<?php echo $lang->translate('Update'); ?>"><i class="icon-pencil"></i></a> 
                </div>			
            </div>
		<?php foreach ($this->ontology_list as $k => $entry): ?> 
		<div class="row-fluid table-bordered-content <?php if(($k)%2): echo "odd"; endif;?>" id="<?php echo $entry['id']; ?>">	
			<div class="span4 pointer"><a class="pointer" id="edit_<?php echo $entry['id'];?>" parent_id="<?php echo $entry['section_parent_id'];?>"> <?php echo $entry['title']; ?> </a></div>
			<div class="span4 last pointer">
			<?php foreach($this->cms_links as $action_id => $opt): ?>
			<?php if($opt['action']=='edit'): ?>
			<a class="pointer" id="edit_<?php echo $entry['id']?>" parent_id="<?php echo $entry['section_parent_id'];?>" title="<?php echo $lang->translate('Update'); ?>"><i class="icon-pencil"></i></a> 
			<?php endif; ?>
			<?php endforeach; ?>	
			</div>			
		</div>					
		<?php endforeach ?>
	</div>
	
</form>	
<?php else: ?>	
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No Sections Found'); ?></h3>
		<!--<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">-->
	</div>	
<?php endif ?>

